### ISSUE TITLE
new registration page breaks this code

### ISSUE THREAD

**Issue by johnnypeste** [ravemir/meo-wifi-login#14]
Hi

Meo changed their registration page (new appearence) and since then the python program does not work anymore...
It says the IP is not from a meo wifi network

Can you confirm and correct

Thanks

**Comment by nunocm** [comment]
I just tried it and it still works (thank you @ravemir!)

You problem @johnnypeste must be another one, since this code is not looking at the login page and instead logs in by making a direct request: 
`GET https://servicoswifi.apps.meo.pt/HotspotConnection.svc/Login?username=' + username+ '&password=' + encrypted_password + '&navigatorLang=pt&callback=foo'`

**Comment by ravemir** [comment]
Thanks for chiming in, @nunocm.

@johnnypeste : can you confirm the message you received is the one from [this line](https://github.com/ravemir/meo-wifi-login/blob/070eb8878998917bed36f81b0ebfa01e7b46cc07/meo_wifi_login.py#L183)?

If so, it might ultimately boil down to not being able to get the IP from [this URL](https://servicoswifi.apps.meo.pt/HotspotConnection.svc/GetState?callback=foo&mobile=false&pagePath=foo), as the code above references.

If it then does come to that, we might need to get to the bottom of why that address does not 
return the IP. Is there a chance you have a different router? Did it happen on all of the routers?

**Comment by ravemir** [comment]
Just did a quick test and, indeed, my router is now redirecting to a different address, and issuing requests to a different endpoint:
![image](https://github.com/user-attachments/assets/da3165c0-342b-4462-a626-69ca099b615e)

The good news is: no password encryption is required now 🎉 
The bad news is: the URL is not fixed, since it contains what looks like is the "session_id" parameter on the payload. Maybe we can generate one for ourselves and it will work?

Will take some time to pick this up, but will report back if I find anything. (currently don't have a working login to test)

**Comment by johnnypeste** [comment]
Here it is my status right now...
Sometimes I get connected, sometimes I don't..

I've  just made a script that is always trying to connect, using the old python grogram


    On Tuesday, July 23, 2024 at 12:52:45 PM UTC, Carlos Filipe Simões ***@***.***> wrote:  
 
 


Just did a quick test and, indeed, my router is now redirecting to a different address, and issuing requests to a different endpoint:
image.png (view on web)

The good news is: no password encryption is required now 🎉
The bad news is: the URL is not fixed, since it contains what looks like is the "session_id" parameter on the payload. Maybe we can generate one for ourselves and it will work?

Will take some time to pick this up, but will report back if I find anything.

**Comment by ravemir** [comment]
So, I did get access to an account and made a couple of discoveries:

1. The new login URL is "https://meowifi.meo.pt/wifim-scl/service/<session_id>/session-login", receiving a POST request containing a JSON payload
2. As stated above, the payload contains not only "userName" and "password" fields (unencrypted), but also "ipAddress" (for the current network adapter), "sessionId" (matching the value on the request address, but maybe not mandatorily) and "loginType" (always set to "login")
3. The first two portions of observed session Id values were always "10" and "F8FE5E26B029", and the last portion was oddly familiar and incrementing
4. After a quick check on an [online unix timestamp converter](https://www.unixtimestamp.com/), I was able to confirm my suspicion that this is indeed the timestamp at the time of the request
5. This makes all parts of the necessary request easily obtainable; despite being present, no other headers or cookies were required

Seeing as there are still reports of the old endpoints lying around, we'd need to leave it in the script as a "legacy" option, but the default could now use the new method.

Will get back to you if there's new developments, but feel free to contribute in the meantime if you feel it within your grasp. :)

**Comment by johnnypeste** [comment]
And what do you conclude after those tests?
The code must be changed?
    On Tuesday, July 23, 2024 at 01:55:49 PM UTC, Carlos Filipe Simões ***@***.***> wrote:  
 
 


So, I did get access to an account and made a couple of discoveries:
   
   - The new login URL is "https://meowifi.meo.pt/wifim-scl/service/<session_id>/session-login", receiving a POST request containing a JSON payload
   - As stated above, the payload contains not only "userName" and "password" fields (unencrypted), but also "ipAddress" (for the current network adapter), "sessionId" (matching the value on the request address, but maybe not mandatorily) and "loginType" (always set to "login")
   - The first two portions of observed session Id values were always "10" and "F8FE5E26B029", and the last portion was oddly familiar and incrementing
   - After a quick check on an online unix timestamp converter, I was able to confirm my suspicion that this is

**Comment by ravemir** [comment]
That was the idea, yes. I have a draft which is already returning status 200 from the endpoint, but not resulting in a login.

Except for me missing the "Content-type" header (which I'd expect Python to add, anyway), I'm not sure what's missing.

Will still work on it a bit more at some other time and update here when I have news.

**Comment by johnnypeste** [comment]
The old python code, sometimes it works sometimes it doesn't...
At this exact moment it's not working.
I think when the login web page is the new one, it dows not work, but sometimes the old login web page ressurects and the code works...


    On Tuesday, July 23, 2024 at 02:33:17 PM UTC, Carlos Filipe Simões ***@***.***> wrote:  
 
 


That was the idea, yes. I have a draft which is already returning status 200 from the endpoint, but not resulting in a login.

Except for me missing the "Content-type" header (which I'd expect Python to add, anyway), I'm not sure what's missing.

**Comment by ravemir** [comment]
Well, it's possible MEO is rolling this out progressively, as opposed to all at once, to prevent any problems with this new portal to cause major disruption. In those scenarios, it's usual to be assigned to both old and new portals intermittently, while the rollout is not done.

I just pushed a new version of the script containing my incomplete draft to the branch attached to this issue. If someone has any ideas as to what may be missing, feel free to chime in.

**Comment by johnnypeste** [comment]
I hope I can see any good news soon... 

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 15:53, Carlos Filipe ***@***.***> wrote:   


Well, it's possible MEO is rolling this out progressively, as opposed to all at once, to prevent any problems with this new portal to cause major disruption. In those scenarios, it's usual to be assigned to both old and new portals intermittently, while the rollout is not done.

I just pushed a new version of the script containing my incomplete draft to the branch attached to this issue. If someone has any ideas as to what may be missing, feel free to chime in.

**Comment by ravemir** [comment]
It's your lucky day, @johnnypeste : just released a new version on that branch that worked for me. Care to try it out, please?

For those that are curious: turns out that the session Id was indeed a Unix timestamp, but we can't just send an arbitrary one (even if current). We need to perform a POST request to the "session-status" endpoint, passing only "ipAddress" this time and, among other things, we will receive a valid token.

Also fixed the logoff option not working, in the process. Will merge if I get positive feedback from other people (or in a couple of days if nobody replies, since my tests did work).

**Comment by johnnypeste** [comment]
I have this scheme on a remote place, so, since the old code doesn't work at this moment I cannot test it

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 16:49, Carlos Filipe ***@***.***> wrote:   


It's your lucky day, @johnnypeste : just released a new version on that branch that worked for me. Care to try it out, please?

For those that are curious: turns out that the session Id was indeed a Unix timestamp, but we can't just send an arbitrary one (even if current). We need to perform a POST request to the "session-status" endpoint, passing only "ipAddress" this time and, among other things, we will receive a valid token.

Also fixed the logoff option not working, in the process. Will merge if I get positive feedback from other people (or in a couple of days if nobody replies, since my tests did work).

**Comment by ravemir** [comment]
Alright: will move ahead with the merge, then, but please let me know how the tests went when you have the chance.

**Comment by johnnypeste** [comment]
But please explain me one thing... the new code will work only when the old code is off (like in this exact moment) or it will work always?

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 17:01, Joao ***@***.***> wrote:   I have this scheme on a remote place, so, since the old code doesn't work at this moment I cannot test it

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 16:49, Carlos Filipe ***@***.***> wrote:   


It's your lucky day, @johnnypeste : just released a new version on that branch that worked for me. Care to try it out, please?

For those that are curious: turns out that the session Id was indeed a Unix timestamp, but we can't just send an arbitrary one (even if current). We need to perform a POST request to the "session-status" endpoint, passing only "ipAddress" this time and, among other things, we will receive a valid token.

Also fixed the logoff option not working, in the process. Will merge if I get positive feedback from other people (or in a couple of days if nobody replies, since my tests did work).

**Comment by ravemir** [comment]
As of my tests, the script will work as it was used before _if_ the new login portal is used. 

_If_ you are connected to a router with the old endpoint, you will now need to pass the '-l' option on the command line (or pass the second parameter of the login/logout functions as 'True').

**Comment by johnnypeste** [comment]
my router is a raspberry pi

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 17:17, Carlos Filipe ***@***.***> wrote:   


As of my tests, the script will work as it was used before if the new login portal is used. If you are connected to a router with the old endpoint, you will now need to pass the '-l' option on the command line (or pass the second parameter of the login/logout functions as 'True').

**Comment by ravemir** [comment]
I meant MEO WiFi router

**Comment by johnnypeste** [comment]
I had an oportunity window and i was able to change the code to the new one...
after that I made a reboot and now I lost connection. I assume since I was connected to the old portal I should use the -l option somehow which I didn't and thats the reason I dont have a conection now that im using the new code... I guess that in 24 h (when im logged out automatically) I will regain access...

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 18:42, Carlos Filipe ***@***.***> wrote:   

I meant MEO WiFi router

**Comment by johnnypeste** [comment]
ok. i have tested on my laptop locally... when the old portal is on, the new code does not work... the old code works... lets wait that the new portal comes alive and check the opposite...

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 24 Jul 2024 at 14:41, Joao ***@***.***> wrote:   I had an oportunity window and i was able to change the code to the new one...
after that I made a reboot and now I lost connection. I assume since I was connected to the old portal I should use the -l option somehow which I didn't and thats the reason I dont have a conection now that im using the new code... I guess that in 24 h (when im logged out automatically) I will regain access...

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 18:42, Carlos Filipe ***@***.***> wrote:   

I meant MEO WiFi router

**Comment by johnnypeste** [comment]
the new code works with the -l flag... sorry... but then, how do i know if i have to use it with the -l or not? do i have to try and error?

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 24 Jul 2024 at 18:57, Joao ***@***.***> wrote:   ok. i have tested on my laptop locally... when the old portal is on, the new code does not work... the old code works... lets wait that the new portal comes alive and check the opposite...

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 24 Jul 2024 at 14:41, Joao ***@***.***> wrote:   I had an oportunity window and i was able to change the code to the new one...
after that I made a reboot and now I lost connection. I assume since I was connected to the old portal I should use the -l option somehow which I didn't and thats the reason I dont have a conection now that im using the new code... I guess that in 24 h (when im logged out automatically) I will regain access...

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 23 Jul 2024 at 18:42, Carlos Filipe ***@***.***> wrote:   

I meant MEO WiFi router

**Comment by ravemir** [comment]
As is, yes. IIRC, there are different exit codes on error, so you can use that on your scripts.

But feel free to contribute if have an idea on how to implement automatic detection. This _is_ open-source, after all.

**Comment by nikito7** [comment]
Avoid to login with smarphone. (Was my trick before)

Working here. More gateways updated.

**Comment by ravemir** [comment]
Cool! Thanks for letting us know.
If I understood correctly, you're saying that the same device can't try to login via the browser, or it will mess up the process? Or that any device logging in in the same network (with the same account, maybe?) will cause issues on another device running this script?

**Comment by nikito7** [comment]
Something like that.
Meo wifi > Openwrt router > wifi > smarphone. 

But maybe it's my issue or wireguard metrics.
Meo use 10.22.x.x subnet.

**Comment by nikito7** [comment]
Still legacy...

Sometimes meo wifi it's down.

```
root@gl1003:~# /root/meo.py -l -u x -p y
<Response [200]>

root@gl1003:~# /root/meo.py -u x -p y
Traceback (most recent call last):
  File "/root/meo.py", line 277, in <module>
    main()
  File "/root/meo.py", line 274, in main
    print(meo_wifi_login(user,passwd, legacy))
  File "/root/meo.py", line 223, in meo_wifi_login
    sessionId = get_session_id(ip)
  File "/root/meo.py", line 205, in get_session_id
    sessionId = response.json()['sessionId']
KeyError: 'sessionId'
root@gl1003:~#
```

It just worked after 2AM...

![Screenshot_20241209_131440_Home Assistant](https://github.com/user-attachments/assets/8d44866f-818a-400e-a06a-cf5b204668fa)

**Comment by nikito7** [comment]
https://github.com/ravemir/meo-wifi-login/issues/14#issue-2342419131
> It says the IP is not from a meo wifi network

I had same message.
Meo wifi down or client blacklisted.

**Comment by nikito7** [comment]
Found my problem....

Two neighbors. One legacy, and the other new page...
